# -*- coding: utf-8 -*-
"""1292.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPorX13K6bTsUBylk5TYXWT5wwtPqV-6
"""

a,b = map(int, input().split())

cnt = 0
num_sum = 0
for i in range(b+1):
  for j in range(i):
    cnt +=1
    if a <= cnt <= b: 
      num_sum = num_sum + i

print(num_sum)

