# -*- coding: utf-8 -*-
"""16953.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19J5eOtaSPmGfEv9atdvZSGqaMxrIefTL
"""

a, b = map(int, input().split()) 
que = [(a, 1)] 
result = -1 

while que: 
  x, cnt = que.pop(0) 
  
  if x == b: 
    result = cnt 
    break 
  
  if x*2 <= b: 
    que.append((x*2, cnt+1)) 
  
  if int(str(x)+'1') <= b: 
    que.append((int(str(x)+'1'), cnt+1)) 
    
print(result)