# -*- coding: utf-8 -*-
"""2178.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1D4igDvij7mGKvIrJ9W3Cx3xpvxZAzr
"""

# 2178
# https://www.acmicpc.net/problem/2178

import sys
from collections import deque

# 괜히 visited가 필요 없었다 메모리초과/시간초과만 생김

n, m = map(int, sys.stdin.readline().split()) 

graph = []
for i in range(n):
  graph.append(list(map(int, sys.stdin.readline().strip()))) # value error 해결

dx = [0, 0, 1, -1]
dy = [1, -1, 0 , 0]

def bfs(x, y):
  queue = deque()
  queue.append((x,y))

  while queue:
    z,w = queue.popleft()

    for i in range(4):
      nx = z + dx[i]
      ny = w + dy[i]

      if nx < 0 or ny < 0 or nx >= n or ny >= m:
        continue
      if graph[nx][ny] == 0:
        continue
      if graph[nx][ny] == 1:
        graph[nx][ny] = graph[z][w] +1
        queue.append((nx,ny))

bfs(0,0)

print(graph[n-1][m-1])