# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4MX1dLs34J2TciBqsm067xgb_ds8BD3
"""

n = int(input())
j = 0

for i in range(n, 0, -1):
  star = "*"
  blank = " "
  print(blank*j+star*(i*2-1))
  j +=1