# -*- coding: utf-8 -*-
"""5598.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7zj0JUEXd6F57ag4ty45ToRvyXA89tM
"""

inp = input()
inp_list = list(inp)
hex_list = []
alpa_list = []
for i in inp_list:
  alpa_ord = ord(i)
  if alpa_ord <= ord('C'):
    alpa_ord = ord(i) + 26
  else: 
    alpa_ord = ord(i)
  hex_list.append(alpa_ord-3)
  
for i in hex_list:
  alpa_list.append(chr(i))

print(''.join(alpa_list))