# -*- coding: utf-8 -*-
"""10872.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-0Ep3Pg5pxX0i2FQDByFGNisnKK9TaJF
"""

n =int(input())

def facto(n):
  if n <= 1:
    return 1
  return n*facto(n-1)

print(facto(n))