# -*- coding: utf-8 -*-
"""1260.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFdBP5NyWdcXQJEhIHF-HgnMjrNFYBPJ
"""

# 1260
# https://www.acmicpc.net/problem/1260

from collections import deque

def dfs(graph, i, visited):
  visited[i] = True
  print(i, end=" ")
  
  for j in graph[i]:
    if not visited[j]:
      dfs(graph, j, visited)


def bfs(graph, i, visited):
  visited[i] = True

  queue = deque([i])
  
  while queue:
    v = queue.popleft()
    print(v, end=" ")
    for j in graph[v]:
      if not visited[j]:
        queue.append(j)
        visited[j] = True

n, m, v = map(int, input().split())

graph = []
visited = [False] * (n+1)

for i in range(n+1):
  graph.append([])

for i in range(m):
  x, y = map(int, input().split())
  graph[x].append(y)
  graph[y].append(x)

for i in graph:
  i.sort()


dfs(graph, v, visited)
visited = [False] * (n+1)
print() # print(" ") <- 이렇게 해서 출력형식이 잘못되었다고 틀렸었다.
bfs(graph, v, visited)

# 왜 이건 안되고
graph = [[]] * (n+1)
print(graph)

graph[1].append(1)
print(graph)

# 이건 되지? 모양은 똑같은데..? 
graph = []
for i in range(n+1):
  graph.append([])

graph[1].append(1)
print(graph)