# -*- coding: utf-8 -*-
"""1697.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wv50TesVfG4vSNXqDKmVItTWyWJsdWd5
"""

# 1697
# https://www.acmicpc.net/problem/1697

from collections import deque

def bfs(n, k):
  global MAX
  queue = deque()
  queue.append(n)

  while queue:
    now = queue.popleft()
    if now == k:
      print(dist[now])
      break
    for nx in (now-1, now+1, now*2): #
      if 0 <= nx <= MAX and not dist[nx]: #
        dist[nx] = dist[now] + 1
        queue.append(nx)

MAX = 100001 # 인덱스에러 해결 
dist = [0] * (MAX+1)

n, k = map(int, input().split())
bfs(n, k)