# -*- coding: utf-8 -*-
"""1978.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQVBm0_KuRUK4Z6s3jKwUdUs5BwRsnq2
"""

n = int(input())
nlist = list(map(int, input().split()))

def is_sosu(x):
  divisors = 0
  if x == 1:
    return False
  for i in range(2, x):
    if x % i == 0:
      divisors +=1
  
  if divisors != 0:
    return False
  else:
    return True

ncnt = 0
for i in nlist:
  if is_sosu(i):
    ncnt +=1

print(ncnt)